repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black . --force-exclude venv
        language: python
        types: [python]
        additional_dependencies: ['black']
      - id: isort
        name: isort
        entry: isort .
        language: python
        types: [python]
        additional_dependencies: ['isort']
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        additional_dependencies: ['flake8']
        files: .py
      - id: pylint
        name: pylint
        entry: ./pylint.sh
        language: system
        types: [python]
        files: .py